---
name: tataku-emitter-nvim_floatwin
description: The emitter module for tataku.vim
--

=pod

=head1 tataku-emitter-nvim_floatwin X<tataku-emitter-nvim_floatwin>

The emitter module that use nvim floatwin for tataku.vim.

=head2 Contents X<tataku-emitter-nvim_floatwin-contents>

=over 0

=item * L<Dependencies|tataku-emitter-nvim_floatwin-dependencies>

=item * L<Options|tataku-emitter-nvim_floatwin-options>

=item * L<Mappings|tataku-emitter-nvim_floatwin-mappings>

=item * L<Samples|tataku-emitter-nvim_floatwin-samples>

=back

=head2 Dependencies X<tataku-emitter-nvim_floatwin-dependencies>

This plugin needs below:

=over 0

=item * L<denops.vim|https://github.com/vim-denops/denops.vim>

=item * L<tataku.vim|https://github.com/Omochice/tataku.vim>

=back

=head2 Options X<tataku-emitter-nvim_floatwin-options>

This module has some options:

=over 0

=item * C<autoclose> X<tataku-emitter-nvim_floatwin-option-autoclose>

  Close automatically when move cursor.
  Default: C<v:true>

=item * C<border> X<tataku-emitter-nvim_floatwin-options-border>

  Border setting for float window.
  This should be C<string>(ref: L<nvim_open_win>)
  or C<dictionary> that have below keys:

=back

=begin typescript

[
	"topleft", "top", "topright", "right",
	"bottomright", "bottom", "bottomleft", "left",
]

=end typescript


=head2 Mappings X<tataku-emitter-nvim_floatwin-mappings>

This module provides below mappings:

=over 0

=item * C<E<lt>PlugE<gt>(tataku-emitter-nvim_floatwin-focus)> X<E<lt>PlugE<gt>(tataku-emitter-nvim_floatwin-focus)>

  Move the cursor into the float window if it is shown.
  The float window is not closed by C<autoclose> while the cursor is in it.

=back

=head2 Samples X<tataku-emitter-nvim_floatwin-samples>

=begin vim

let g:tataku_recipes = #{
  \   sample: #{
  \     emitter: #{
  \       name: 'nvim_floatwin',
  \       options: #{ border: 'single', autoclose: v:true, },
  \     },
  \   },
  \ }

nmap <C-w>p <Plug>(tataku-emitter-nvim_floatwin-focus)

=end vim

=cut
